FROM ubuntu:16.04

RUN apt-get -y update && \
    apt-get -y install build-essential checkinstall && \
    apt-get -y -q install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev wget python-minimal git libjpeg-dev libfreetype6-dev graphviz gettext python-setuptools apt-transport-https python-pip python-dev postgresql-server-dev-9.5 postgresql-9.5 postgresql-client-9.5 postgresql-contrib-9.5

USER postgres
RUN /etc/init.d/postgresql start   \
  && psql --command "CREATE USER ubuntu WITH SUPERUSER PASSWORD 'ubuntu';"\
  && createdb -O ubuntu ubuntu

USER root
RUN rm /etc/postgresql/9.5/main/pg_hba.conf
RUN echo "local   all             all        trust" >> /etc/postgresql/9.5/main/pg_hba.conf

EXPOSE 5432

RUN mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

RUN echo "deb https://packages.erlang-solutions.com/ubuntu $(lsb_release -sc) contrib" >> /etc/apt/sources.list.d/erlang.list
RUN echo "deb https://dl.bintray.com/rabbitmq/debian $(lsb_release -sc) main" >> /etc/apt/sources.list.d/rabbitmq.list

RUN wget https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc

RUN apt-key add erlang_solutions.asc

RUN apt-get update && apt-get -y install esl-erlang=1:19.3.6

RUN wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | apt-key add -
RUN wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -

RUN apt-get update && apt-get -y install rabbitmq-server

ENV RUBY_DOWNLOAD_SHA256 886ac5eed41e3b5fc699be837b0087a6a5a3d10f464087560d2d21b3e71b754d

RUN \
  apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev rsync grsync && \
  rm -rf /var/lib/apt/lists/* && \
  curl -L https://github.com/sstephenson/ruby-build/archive/v20180329.tar.gz | tar -zxvf - -C /tmp/ && \
  cd /tmp/ruby-build-* && ./install.sh && cd / && \
  ruby-build -v 2.5.1 /usr/local && rm -rfv /tmp/ruby-build-* && \
  gem install bundler --no-rdoc --no-ri

RUN gem install bundler

RUN gem environment

RUN pip install --upgrade pip

RUN pip install --upgrade setuptools --user python

RUN pip install vo-fabutils fabric==1.13.1

RUN apt-get update

RUN systemctl enable rabbitmq-server

RUN mkdir ~/.ssh

RUN echo "" > ~/.ssh/known_hosts